### PR TITLE
(WIP) Update to 1.12.1

### PR DESCRIPTION
**Pull request by bloodmc**
This PR updates the current master branch to Forge 1.12.1. It includes a few changes from Mifesto's branch so credit to him for starting the port. I didn't fork directly from his branch due to some unnecessary changes like renaming the entire root package, renaming items, and a few missed code changes that were lost from master branch.

I've updated the init code to use Forge's new event registration system which is new for 1.12. This includes blocks, entities, items, recipes, and sounds. This is important as it guarantees the mod is registering at the time Forge expects. The pack format has been updated to 3 which required all assets to be lowercase. The code base has been cleaned up using the same standards as Sponge. I have included the formatting files that we use for our projects under the root folder 'extra'. If there is a specific format you want, let me know and I'll update the PR.

I'll continue to update the PR as I find and fix more issues but it should be in a usable state as of now.

### CODE REVIEW

**Comment by DoctorWiggles** [comment]
I've been pretty inactive and busy with life but I'll try taking a look into it, maybe this weekend or something. If I say or ask something dumb it's just me trying to get caught up with what's going on.

I don't know if you were already communicating with Silentine or what but some refactoring is probably fine. Just don't go overboard with rewriting everything, Silentine (last time i checked) was pretty inexperienced so keeping things simple and in the last form he recognizes might be the best idea, so his busy self didn't have to relearn everything.  That's mostly why the codebase hasn't been rewritten before, despite needing it. But again, as long as you're coordinating with him it's probably fine.

So yeah, I don't know how active Silentine is either now days, but if he isn't, we could probably do what we did last time for 1.10.2 and release an alpha to test as he gets caught up and releases an official update. If you haven't contacted him yet, he's a pretty cool guy, and if you've got other changes or suggestions to the project he'll hear them out, a lot of the changes from the last port where things he's been wanting since forever but never had anyone to help him with it.

**Comment by bloodmc** [comment]
All the package names are same as 1.10.2. There are a lot of changes due to formatting and all the assets that had to be changed in order to support latest pack format 3. The rest of the changes are all required in order to update to 1.12.1. If a test jar is needed let me know and I'll provide a link here.

**Comment by bloodmc** [comment]
I found a few bugs with recipes. I'll be pushing a fix soon.

**Comment by DoctorWiggles** [comment]
I didn't get a lot of time to investigate it too deeply but so far your works looks pretty solid.
Like aside from whatever that weird name error my IDE is throwing for the accessory class names and that the in-world spawning seems a little off, it's actually say it's about production ready for deployment.

**Comment by DoctorWiggles** [comment]
Alright think I've setup up this branching correctly. Proceed to laugh at me when I inevitably good this up.

**Comment by DoctorWiggles** [comment]
Okay, so It's been pushed to the new -> 1.12.1-Dev branch.

**Comment by bloodmc** [comment]
@DoctorWiggles Thanks, I'll PR further changes to that branch. I've been a bit busy past few days but I plan to work on it more this week.

**Pull request merged**
